
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Begin Jekyll SEO tag v2.8.0 -->
<title>test</title>
<meta name="generator" content="Jekyll v3.9.2">
<meta property="og:title" content="re">
<meta property="og:locale" content="en_US">
<link rel="canonical" href="https://timotherenard.github.io/re/">
<meta property="og:url" content="https://timotherenard.github.io/re/">
<meta property="og:site_name" content="re">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary">
<meta property="twitter:title" content="re">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebSite","headline":"re","name":"re","url":"https://timotherenard.github.io/re/"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="/re/assets/css/style.css?v=ec09f935f41811b60efedc4c4d14456041c5db65">
    <!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->



<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="/re/favicon.ico" -->

<!-- end custom head snippets -->

  
